# OpenCV2   📸📸📸
- OpenCV (cv2), short for Open Source Computer Vision Library, is a popular open-source library used for computer vision and image processing tasks. It provides a wide range of functionalities to work with images and videos, making it a valuable tool for tasks such as object detection, facial recognition, image manipulation, and more

#### <center><img src= 'https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExMjliZ2IxMm5jdGtsNTlocmE4NW15MGllZjZpamRlejRqeTRuOGY1NyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/K5DhLPHVVRrNW7nhfy/giphy.gif' width="200"></center>

In [1]:
import cv2 as cv
import numpy as np

### Face detection

- Here we open the camera in real time then by fixing the coordinates or the size of the camera we can clik the images at real time
- to come out from this click on keyboard --> 'enter'

In [10]:
classifier = cv.CascadeClassifier(r"C:\Users\user\Downloads\haarcascade_frontalface_default.xml")

cam = cv.VideoCapture(0)

while True:
    _, img = cam.read()
    img = cv.flip(img,1)
    
    
    try:
        faces = classifier.detectMultiScale(img, 1.1,8) 
        for(x,y,w,h) in faces:
            cv.rectangle(img, (x,y),(x+w,y+w),(0,180,0),5)
            
            
    except:
        pass
    
    cv.imshow('Frame', img)
    
    
    
    if(cv.waitKey(1) == 27):
        cam.release()
        break

In [11]:
cv.destroyAllWindows()

### Croping the detected face

- After the clicking from the camera now Crop the image by palying with the index values of the generated image

In [14]:
classifier = cv.CascadeClassifier(r"C:\Users\user\Downloads\haarcascade_frontalface_default.xml")

cam = cv.VideoCapture(0)

while True:
    _, img = cam.read()
    img = cv.flip(img,1)
    
    faces = classifier.detectMultiScale(img, 1.1,5) 
    
    for face in faces:
        if face[-1] == max(faces[:,-1]):
            print(face)
    if len(faces) >= 1 :
        for(x,y,w,h) in faces:
            cv.rectangle(img, (x,y),(x+w,y+w),(0,180,0),5)
            face = img[y:y+h, x:x+w]
     
    cv.imshow('Frame', img)
    cv.imshow('Face', face)
    
    
    
    if(cv.waitKey(1) == 27):
        cam.release()
        break

[102 174 271 271]
[105 174 270 270]
[102 171 271 271]
[104 172 271 271]
[101 172 274 274]
[101 172 269 269]
[101 174 270 270]
[104 174 265 265]
[ 97 172 272 272]
[101 175 264 264]
[ 97 172 276 276]
[101 177 263 263]
[ 99 174 272 272]
[ 98 173 266 266]
[ 98 172 272 272]
[ 98 173 269 269]
[100 172 269 269]
[ 96 171 271 271]
[108 163 265 265]
[112 161 264 264]
[133 143 254 254]
[142 145 239 239]
[158 130 245 245]
[158 127 249 249]
[158 131 261 261]
[159 132 277 277]
[159 136 271 271]
[162 141 264 264]
[155 138 286 286]
[157 144 272 272]
[153 142 289 289]
[153 135 298 298]
[157 136 298 298]
[152 140 297 297]
[154 141 295 295]
[154 140 299 299]
[156 142 295 295]
[159 144 292 292]
[161 145 292 292]
[163 143 294 294]
[166 148 284 284]
[158 141 292 292]
[158 142 290 290]
[167 148 280 280]
[156 140 297 297]
[153 140 300 300]
[154 139 299 299]
[152 140 302 302]
[155 142 292 292]
[153 140 298 298]
[155 141 294 294]
[156 141 287 287]
[159 142 290 290]
[168 150 273 273]
[159 147 276 276]
[162 151 2

### Blur the detected face

- For blur the image just decrease the pixel value of the each index value of the image 
- adjust the index value as your reqired need.

In [21]:
classifier = cv.CascadeClassifier(r"C:\Users\user\Downloads\haarcascade_frontalface_default.xml")

cam = cv.VideoCapture(0)

while True:
    _, img = cam.read()
    img = cv.flip(img,1)
    
    faces = classifier.detectMultiScale(img, 1.1,5) 
    
    for face in faces:
        if face[-1] == max(faces[:,-1]):
            print(face)
    if len(faces) >= 1 :
        for(x,y,w,h) in faces:
#            cv.rectangle(img, (x,y),(x+w,y+w),(0,180,0),5)
            face = img[y-50:y+h+50, x:x+w]
            face = cv.blur(face, (32,32))
        img[y-50:y+h+50,x:x+w] = face
    
     
    cv.imshow('Frame', img)
    cv.imshow('Face', face)
    
    
    
    if(cv.waitKey(1) == 27):
        cam.release()
        break

[126 170 249 249]
[128 171 247 247]
[129 170 246 246]
[131 173 243 243]
[130 172 247 247]
[126 171 248 248]
[131 170 256 256]
[131 173 253 253]
[133 171 258 258]
[134 174 255 255]
[123 168 258 258]
[128 173 251 251]
[121 170 256 256]
[122 174 252 252]
[124 174 252 252]
[128 174 250 250]
[129 174 249 249]
[135 175 253 253]
[132 174 255 255]
[131 173 256 256]
[136 179 244 244]
[134 174 251 251]
[130 174 254 254]
[130 173 253 253]
[127 174 253 253]
[127 176 247 247]
[126 176 248 248]
[123 176 249 249]
[124 178 244 244]
[116 173 248 248]
[113 173 247 247]
[111 174 246 246]
[111 173 242 242]
[106 172 249 249]
[108 171 245 245]
[109 173 247 247]
[105 173 253 253]
[107 182 251 251]
[107 181 247 247]
[111 188 246 246]
[106 184 255 255]
[121 189 249 249]
[124 184 250 250]
[123 180 256 256]
[129 178 250 250]
[131 179 246 246]
[132 177 238 238]
[127 174 237 237]
[121 167 235 235]
[123 166 240 240]
[120 160 237 237]
[125 154 238 238]
[121 149 238 238]
[129 146 239 239]
[131 149 235 235]
[132 147 2

### RealTime Face Black   By Rectangle

- Many times we see in videos the face of the object is blacked 
- We can also do it by changing all the pixel values to the 0 in RGB
- That will help to get the black image face

In [23]:
classifier = cv.CascadeClassifier(r"C:\Users\user\Downloads\haarcascade_frontalface_default.xml")

cam = cv.VideoCapture(0)

while True:
    _, img = cam.read()
    img = cv.flip(img,1)
    
    faces = classifier.detectMultiScale(img, 1.1,5) 
    
    for face in faces:
        if face[-1] == max(faces[:,-1]):
            break
            
    
    for(x,y,w,h) in faces:
        face = img[y:y+h,x:x+w]
        
    black = np.zeros((face.shape), dtype = int)
    
    img[y:y+h,x:x+w] = black
    
    cv.imshow('Frame', img)
    ##cv.imshow('Face', face)
    
    if(cv.waitKey(1) == 27):
        cam.release()
        break

In [24]:
cv.destroyAllWindows()

### By Circle Black
- Done the same job but by using the circle
- to apply the circle find the middle value by the coordinates of ranctangle and then chhose the radius

In [30]:
classifier = cv.CascadeClassifier(r"C:\Users\user\Downloads\haarcascade_frontalface_default.xml")

cam = cv.VideoCapture(0)

while True:
    _, img = cam.read()
    img = cv.flip(img,1)
    
    faces = classifier.detectMultiScale(img, 1.1,5) 
    
    for face in faces:
        if face[-1] == max(faces[:,-1]):
            break
            
    
    x = face[0]
    y = face[1]
    w = face[2]
    h = face[3]
    
    circle_x = x + int(w/2)
    circle_y = y + int(h/2)
    
    cv.circle(img,(circle_x,circle_y), int(w/1.5), (0,180,0),-1)
    
    cv.imshow('Frame', img)
    
    if(cv.waitKey(1) == 27):
        cam.release()
        break

In [31]:
cv.destroyAllWindows()

### Croping the face from the image
- In this task crop faces of the multiple man detected from the image
- just load the image path then by enter and delete choose the croped image that will be stored or not
- After croping the image store it into the local file/ folder

In [34]:
import os


In [44]:
img = cv.imread(r'C:\Users\user\OneDrive\Pictures\IMG_20230108_112132_690.jpg')

classifier = cv.CascadeClassifier(r"C:\Users\user\Downloads\haarcascade_frontalface_default.xml")
faces = classifier.detectMultiScale(img, 1.1,5)

def save(frame, folder_name):
    name_img = len(os.listdir(folder_name)) + 1
    name_img = folder_name + '/IMG_' + str(name_img) + '.png'
    cv.imwrite(name_img, frame)
    print(name_img , ' is exported')

for(x,y,w,h) in faces:
    face = img[y:y+h,x:x+w]
    cv.imshow('Face', face)
    
    if cv.waitKey(0) == 13:         ## Save Image 13 -> enter
        save(face,r"C:\Users\user\OneDrive\Desktop\New folder")
    elif cv.waitKey(0) == 127:      ## Skip Image 127 -> delete
        pass
    
    
   

In [40]:
cv.destroyAllWindows()

## Conclusion 🖊️🖊️🖊️🖊️

- By the opencv library it will help to work with thw image file, it will alow us to work with image processing techniq
- For any kind of information regarding project comment on [LinkedIn](https://www.linkedin.com/in/ashu-toshkr)